name: fstapp
description: Guide for the event/festival/conference.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.15.3+165

environment:
  sdk: '>=2.19.5 <3.22.1'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  fluttertoast: 8.2.12

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_marker_popup: ^7.0.0
#  flutter_map_marker_popup:
#    path: ./pckgs/flutter_map_marker_popup-master
  supabase_flutter: ^2.9.1
  flutter_secure_storage: ^10.0.0-beta.4
  timelines_plus: ^1.0.7
  intl: ^0.20.2
  search_page: ^2.3.0
  badges: ^3.1.1
  collection: ^1.18.0
  flutter_map_location_marker: ^9.1.1
  geolocator: ^13.0.4
  flutter_widget_from_html: ^0.16.0
  quill_html_editor:
    git:
      url: https://github.com/the-airbender/quill_html_editor.git
      ref: a2beeb5bfd436e86f2635c8db1154b4190eeedb5
  trina_grid: ^1.6.9
  url_strategy: ^0.3.0
  desktop_drop: ^0.6.0
  csv: ^6.0.0
  sembast: ^3.8.5
  sembast_web: ^2.4.1
  path_provider: ^2.1.5
  select_dialog: ^2.0.1
  onesignal_flutter: ^5.3.2
  package_info_plus: ^8.3.0
  flutter_animate: ^4.5.2
  easy_localization: ^3.0.7
  flutter_map_cancellable_tile_provider: ^3.0.2
  simple_shadow: ^0.3.1
  pwa_install:
    git:
      url: https://github.com/jtmuller5/pwa_install.git
      ref: 82320a219574c1b5ddf1d83e080cad5a84261c2d
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.2.0
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  mobile_scanner: ^7.0.1
  flutter_map_animations: ^0.8.0
  auto_route: ^10.1.0
  adaptive_theme: ^3.7.0
  connectivity_plus: ^6.1.4
  vector_map_tiles_mbtiles: ^1.2.0
  vector_map_tiles: ^8.0.0
  mbtiles: ^0.4.0
  sqlite3_flutter_libs: ^0.5.32
  file_saver: ^0.3.0
  youtube_player_flutter: ^9.1.1
#    git:
#      url: https://github.com/MusabBoltX/youtube_player_flutter_patch_fix.git
#      ref: 97b3618b9891eb2b05a1b71ee75c432a2dce6d1a
  flutter_widget_from_html_core: ^0.16.0
  fwfh_cached_network_image: ^0.16.0
  multi_split_view: ^3.6.0
  timezone: ^0.10.1

dev_dependencies:
  auto_route_generator: ^10.1.0
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Futura
      fonts:
        - asset: fonts/Futura PT Book.ttf
        - asset: fonts/Futura PT Medium.ttf
  assets:
    - assets/icons/
    - assets/translations/
    - packages/timezone/data/latest.tzf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
